name: CI-CD Production Pipeline
on:
  push:
    branches: [ "main" ]
jobs:
  continuous-integration:
    runs-on: self-hosted
    steps:
    - name: Run direct local command
      shell: cmd
      run: echo Hello Mohamed, Odoo pipeline is running locally on Windows cmd!