name: Odoo CI-CD Production Pipeline
on:
  push:
    branches: [ "main" ]
jobs:
  continuous-integration:
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Run local test command
      run: echo "Hello Muhammad, Odoo pipeline is running locally on your machine!"